apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.frontend }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tier: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.backend }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tier: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.database }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    tier: database
