helm:
  parameters:
  - name: backend.image.tag
    value: v1.0.15
    forcestring: true
  - name: frontend.image.tag
    value: v1.0.15
    forcestring: true
  - name: image.name
    value: maqsoodbangash/food-frontend
    forcestring: true
