apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: three-tier-app-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "three-tier-app"
      useAnnotations: true
