apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespaces.frontend }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
          env:
            - name: BACKEND_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_API_BASE_URL
