{{- range list .Values.namespaces.database .Values.namespaces.backend }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ . }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ $.Values.mongo.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ $.Values.mongo.password | quote }}
  MONGO_URI: "mongodb://{{ $.Values.mongo.username }}:{{ $.Values.mongo.password }}@mongo-0.mongo-service.{{ $.Values.namespaces.database }}.svc.cluster.local:27017/?authSource=admin&replicaSet={{ $.Values.mongo.replicaSetName }}"
---
{{- end }}
