apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: food-delivery
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "food-frontend=maqsoodbangash/food-frontend"
    argocd-image-updater.argoproj.io/food-delivery.update-strategy: "semver"
    argocd-image-updater.argoproj.io/food-delivery.allow-tags: "regexp:^v?\\d+\\.\\d+\\.\\d+$"


    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: feature/Maqsood-khan
spec:
  project: default
  source:
    repoURL: https://github.com/Mr-Maqsood-Bangash/Food-Delivery.git
    path: .
    targetRevision: feature/Maqsood-khan
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

